{% set version = "1.4.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rpresto
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RPresto_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RPresto/RPresto_{{ version }}.tar.gz
  sha256: f8f3f4e5704d82a084b7b4ef6c9df433be67f24b779084c49866f2dcbe7c37d9

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dbi >=0.3.0
    - r-bit64
    - r-dbplyr >=2.0.0
    - r-dplyr >=0.7.0
    - r-httr >=0.6
    - r-jsonlite
    - r-lifecycle
    - r-lubridate
    - r-openssl
    - r-progress
    - r-purrr
    - r-rlang
    - r-stringi
    - r-tibble
  run:
    - r-base
    - r-dbi >=0.3.0
    - r-bit64
    - r-dbplyr >=2.0.0
    - r-dplyr >=0.7.0
    - r-httr >=0.6
    - r-jsonlite
    - r-lifecycle
    - r-lubridate
    - r-openssl
    - r-progress
    - r-purrr
    - r-rlang
    - r-stringi
    - r-tibble

test:
  commands:
    - $R -e "library('RPresto')"           # [not win]
    - "\"%R%\" -e \"library('RPresto')\""  # [win]

about:
  home: https://github.com/prestodb/RPresto
  license: BSD-3-Clause
  summary: "Implements a 'DBI' compliant interface to Presto. Presto is an open source distributed SQL query engine for running interactive analytic queries against data sources of all sizes ranging from gigabytes to petabytes: <https://prestodb.io/>."
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - RyanHackney
    - rluria14
    - ndmaxar
    - Oblute

# Package: RPresto
# Title: DBI Connector to Presto
# Version: 1.3.4
# Authors@R: c( person('Onur Ismail', 'Filiz', , 'onur@fb.com', role=c('aut', 'cre')), person('Sergey', 'Goder', , 'sgoder@fb.com', role='aut'), person('John Myles', 'White', , 'johnmyleswhite@fb.com', role='ctb') )
# Copyright: Facebook, Inc. 2015-present.
# Description: Implements a 'DBI' compliant interface to Presto. Presto is an open source distributed SQL query engine for running interactive analytic queries against data sources of all sizes ranging from gigabytes to petabytes: <https://prestodb.io/>.
# Depends: R (>= 3.1.0), methods
# Imports: DBI (>= 0.3.0), httr (>= 0.6), openssl, jsonlite, stringi, stats, Rcpp (>= 0.12.7), utils
# Suggests: testthat, dplyr (>= 0.7.0), dbplyr
# License: BSD_3_clause + file LICENSE
# URL: https://github.com/prestodb/RPresto
# BugReports: https://github.com/prestodb/RPresto/issues
# Encoding: UTF-8
# LazyData: true
# Collate: 'PrestoDriver.R' 'Presto.R' 'utility_functions.R' 'PrestoSession.R' 'PrestoConnection.R' 'PrestoCursor.R' 'PrestoResult.R' 'RcppExports.R' 'src.presto.R' 'copy.to.src.presto.R' 'db.data.type.PrestoConnection.R' 'dbplyr_compatible.R' 'db.explain.PrestoConnection.R' 'db.query.rows.PrestoConnection.R' 'request_headers.R' 'dbHasCompleted.R' 'dbClearResult.R' 'dbConnect.R' 'dbDataType.R' 'dbDisconnect.R' 'dbSendQuery.R' 'json.tabular.to.data.frame.R' 'extract.data.R' 'parse.response.R' 'dbFetch.R' 'dbGetQuery.R' 'dbListTables.R' 'dbExistsTable.R' 'dbGetInfo.R' 'dbGetRowCount.R' 'dbGetStatement.R' 'dbIsValid.R' 'dbListFields.R' 'dbUnloadDriver.R' 'description_from_info.R' 'db_desc.PrestoConnection.R' 'db_query_fields.R' 'fetch.R' 'help.R' 'sql_translate_env.R' 'tbl.src.presto.R'
# RoxygenNote: 6.1.1
# LinkingTo: Rcpp
# NeedsCompilation: yes
# Packaged: 2019-10-18 16:03:01 UTC; onur
# Author: Onur Ismail Filiz [aut, cre], Sergey Goder [aut], John Myles White [ctb]
# Maintainer: Onur Ismail Filiz <onur@fb.com>
# Repository: CRAN
# Date/Publication: 2019-10-18 17:40:03 UTC
